FROM centos

RUN yum install -y wget

RUN mkdir /var/tmp/jdk
RUN wget --no-check-certificate --no-cookies --header \
    "Cookie: gpw_e24=https%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
    -P /var/tmp/jdk/jdk-8.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-i586.tar.gz
RUN cd /var/tmp/jdk && ls -a -l
RUN tar xzf /var/tmp/jdk/jdk-8.tar.gz/jdk-8u181-linux-i586.tar.gz -C /var/tmp/jdk \
    && rm -rf /var/tmp/jdk/jdk-8.tar.gz/jdk-8u181-linux-i586.tar.gz
RUN cd /var/tmp/jdk && ls -a -l

ENV JAVA_HOME /var/tmp/jdk/jdk-8.tar.gz/jdk1.8.0_181
ENV PATH $PATH:${JAVA_HOME}/bin

RUN echo $PATH
RUN java -version
