version: '3'
services:
  web:
    image: kelvinmai/swamdemo:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9090:8090"
#    volumes:
#      - ./buildDir/res:/usr/res
    networks:
      - webnet
networks:
  webnet:
